version: "3.3"

services:
  postgres:
    container_name: sbs_postgres
    image: "postgres:13.3"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spring_boot_simple
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring-boot-simple

networks:
  spring-boot-simple:
